/// Maps allergy/preference tags to ingredient keywords for matching.
const Map<String, List<String>> allergyTagKeywords = {
  'Gluten': [
    'flour',
    'bread',
    'pasta',
    'noodle',
    'wheat',
    'barley',
    'rye',
    'spelt',
    'semolina',
    'couscous',
    'cracker',
    'biscuit',
    'cake',
    'pastry',
    'malt',
    'seitan',
    'bulgur',
    'farro',
    'beer'
  ],
  'Lactose': [
    'milk',
    'cheese',
    'butter',
    'cream',
    'yogurt',
    'whey',
    'casein',
    'ghee',
    'curd',
    'dairy'
  ],
  'Peanuts': ['peanut', 'groundnut'],
  'Tree Nuts': [
    'almond',
    'walnut',
    'cashew',
    'pecan',
    'hazelnut',
    'macadamia',
    'pistachio',
    'brazil nut',
    'chestnut',
    'nut'
  ],
  'Eggs': ['egg'],
  'Fish': [
    'fish',
    'anchovy',
    'salmon',
    'tuna',
    'cod',
    'trout',
    'sardine',
    'herring',
    'mackerel'
  ],
  'Shellfish': [
    'shrimp',
    'prawn',
    'crab',
    'lobster',
    'scallop',
    'clam',
    'mussel',
    'oyster',
    'shellfish'
  ],
  'Soy': ['soy', 'soya', 'tofu', 'edamame', 'miso', 'tempeh'],
  'Sesame': ['sesame', 'tahini'],
  'Dairy': [
    'milk',
    'cheese',
    'butter',
    'cream',
    'yogurt',
    'whey',
    'casein',
    'ghee',
    'curd',
    'dairy'
  ],
  'Wheat': [
    'wheat',
    'flour',
    'bread',
    'pasta',
    'noodle',
    'semolina',
    'couscous',
    'cracker',
    'biscuit',
    'cake',
    'pastry',
    'bulgur',
    'farro'
  ],
  'Mustard': ['mustard'],
  'Celery': ['celery'],
  'Sulphites': ['sulphite', 'sulfite', 'preservative'],
  'Lupin': ['lupin'],
  'Molluscs': [
    'mollusc',
    'octopus',
    'squid',
    'snail',
    'clam',
    'oyster',
    'scallop',
    'mussel'
  ],
};

const Map<String, List<String>> preferenceTagKeywords = {
  'Halal': [
    'pork',
    'ham',
    'bacon',
    'lard',
    'gelatin',
    'alcohol',
    'beer',
    'wine',
    'rum',
    'whiskey',
    'vodka',
    'gin',
    'brandy',
    'liqueur',
    'vermouth',
    'schnapps',
    'cognac',
    'tequila',
    'bourbon',
    'prosecco',
    'champagne',
    'cider',
    'sake',
    'soju',
    'absinthe',
    'mead',
    'cocktail',
    'spirit',
    'blood',
    'non-halal'
  ],
  'Kosher': [
    'pork',
    'ham',
    'bacon',
    'lard',
    'shellfish',
    'shrimp',
    'crab',
    'lobster',
    'clam',
    'oyster',
    'scallop',
    'mussel',
    'gelatin',
    'non-kosher'
  ],
  'Vegan': [
    'meat',
    'chicken',
    'beef',
    'pork',
    'fish',
    'egg',
    'milk',
    'cheese',
    'butter',
    'cream',
    'yogurt',
    'honey',
    'gelatin',
    'seafood',
    'shrimp',
    'crab',
    'lobster',
    'anchovy',
    'sardine',
    'animal',
    'dairy',
    'lard',
    'casein',
    'whey',
    'curd',
    'ghee',
    'non-vegan'
  ],
  'Vegetarian': [
    'meat',
    'chicken',
    'beef',
    'pork',
    'fish',
    'seafood',
    'shrimp',
    'crab',
    'lobster',
    'anchovy',
    'sardine',
    'gelatin',
    'animal',
    'lard',
    'non-vegetarian'
  ],
  'Pescatarian': [
    'meat',
    'chicken',
    'beef',
    'pork',
    'lamb',
    'duck',
    'turkey',
    'venison',
    'rabbit',
    'goat',
    'gelatin',
    'animal',
    'lard',
    'non-pescatarian'
  ],
  'Dairy-Free': [
    'milk',
    'cheese',
    'butter',
    'cream',
    'yogurt',
    'whey',
    'casein',
    'ghee',
    'curd',
    'dairy'
  ],
  'Gluten-Free': [
    'flour',
    'bread',
    'pasta',
    'noodle',
    'wheat',
    'barley',
    'rye',
    'spelt',
    'semolina',
    'couscous',
    'cracker',
    'biscuit',
    'cake',
    'pastry',
    'malt',
    'seitan',
    'bulgur',
    'farro',
    'beer'
  ],
  // Add more as needed
};
